/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppStatesRouteImport } from './routes/_app.states'
import { Route as AppAssignmentSuccessRouteImport } from './routes/_app.assignment.success'
import { Route as AppBookingsIndexRouteImport } from './routes/_app.bookings.index'
import { Route as AppBookingsIdRouteImport } from './routes/_app.bookings.$id'
import { Route as AppDriversIndexRouteImport } from './routes/_app.drivers.index'
import { Route as AppDriversIdRouteImport } from './routes/_app.drivers.$id'
import { Route as AppJobsNewRouteImport } from './routes/_app.jobs.new'
import { Route as AppZonesIndexRouteImport } from './routes/_app.zones.index'
import { Route as AppZonesIdRouteImport } from './routes/_app.zones.$id'
import { Route as AppBookingsIdIndexRouteImport } from './routes/_app.bookings.$id.index'
import { Route as AppBookingsIdAssignRouteImport } from './routes/_app.bookings.$id.assign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppStatesRoute = AppStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentSuccessRoute = AppAssignmentSuccessRouteImport.update({
  id: '/assignment/success',
  path: '/assignment/success',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIndexRoute = AppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIdRoute = AppBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversIndexRoute = AppDriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversIdRoute = AppDriversIdRouteImport.update({
  id: '/drivers/$id',
  path: '/drivers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppZonesIndexRoute = AppZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => AppRoute,
} as any)
const AppZonesIdRoute = AppZonesIdRouteImport.update({
  id: '/zones/$id',
  path: '/zones/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIdIndexRoute = AppBookingsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBookingsIdRoute,
} as any)
const AppBookingsIdAssignRoute = AppBookingsIdAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => AppBookingsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notifications': typeof AppNotificationsRoute
  '/overview': typeof AppOverviewRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/states': typeof AppStatesRoute
  '/assignment/success': typeof AppAssignmentSuccessRoute
  '/bookings/$id': typeof AppBookingsIdRouteWithChildren
  '/drivers/$id': typeof AppDriversIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/zones/$id': typeof AppZonesIdRoute
  '/bookings/': typeof AppBookingsIndexRoute
  '/drivers/': typeof AppDriversIndexRoute
  '/zones/': typeof AppZonesIndexRoute
  '/bookings/$id/assign': typeof AppBookingsIdAssignRoute
  '/bookings/$id/': typeof AppBookingsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notifications': typeof AppNotificationsRoute
  '/overview': typeof AppOverviewRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/states': typeof AppStatesRoute
  '/assignment/success': typeof AppAssignmentSuccessRoute
  '/drivers/$id': typeof AppDriversIdRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/zones/$id': typeof AppZonesIdRoute
  '/bookings': typeof AppBookingsIndexRoute
  '/drivers': typeof AppDriversIndexRoute
  '/zones': typeof AppZonesIndexRoute
  '/bookings/$id/assign': typeof AppBookingsIdAssignRoute
  '/bookings/$id': typeof AppBookingsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/states': typeof AppStatesRoute
  '/_app/assignment/success': typeof AppAssignmentSuccessRoute
  '/_app/bookings/$id': typeof AppBookingsIdRouteWithChildren
  '/_app/drivers/$id': typeof AppDriversIdRoute
  '/_app/jobs/new': typeof AppJobsNewRoute
  '/_app/zones/$id': typeof AppZonesIdRoute
  '/_app/bookings/': typeof AppBookingsIndexRoute
  '/_app/drivers/': typeof AppDriversIndexRoute
  '/_app/zones/': typeof AppZonesIndexRoute
  '/_app/bookings/$id/assign': typeof AppBookingsIdAssignRoute
  '/_app/bookings/$id/': typeof AppBookingsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notifications'
    | '/overview'
    | '/profile'
    | '/search'
    | '/states'
    | '/assignment/success'
    | '/bookings/$id'
    | '/drivers/$id'
    | '/jobs/new'
    | '/zones/$id'
    | '/bookings/'
    | '/drivers/'
    | '/zones/'
    | '/bookings/$id/assign'
    | '/bookings/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notifications'
    | '/overview'
    | '/profile'
    | '/search'
    | '/states'
    | '/assignment/success'
    | '/drivers/$id'
    | '/jobs/new'
    | '/zones/$id'
    | '/bookings'
    | '/drivers'
    | '/zones'
    | '/bookings/$id/assign'
    | '/bookings/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/notifications'
    | '/_app/overview'
    | '/_app/profile'
    | '/_app/search'
    | '/_app/states'
    | '/_app/assignment/success'
    | '/_app/bookings/$id'
    | '/_app/drivers/$id'
    | '/_app/jobs/new'
    | '/_app/zones/$id'
    | '/_app/bookings/'
    | '/_app/drivers/'
    | '/_app/zones/'
    | '/_app/bookings/$id/assign'
    | '/_app/bookings/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/states': {
      id: '/_app/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof AppStatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignment/success': {
      id: '/_app/assignment/success'
      path: '/assignment/success'
      fullPath: '/assignment/success'
      preLoaderRoute: typeof AppAssignmentSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings/': {
      id: '/_app/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AppBookingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings/$id': {
      id: '/_app/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AppBookingsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers/': {
      id: '/_app/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AppDriversIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers/$id': {
      id: '/_app/drivers/$id'
      path: '/drivers/$id'
      fullPath: '/drivers/$id'
      preLoaderRoute: typeof AppDriversIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/new': {
      id: '/_app/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/zones/': {
      id: '/_app/zones/'
      path: '/zones'
      fullPath: '/zones/'
      preLoaderRoute: typeof AppZonesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/zones/$id': {
      id: '/_app/zones/$id'
      path: '/zones/$id'
      fullPath: '/zones/$id'
      preLoaderRoute: typeof AppZonesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings/$id/': {
      id: '/_app/bookings/$id/'
      path: '/'
      fullPath: '/bookings/$id/'
      preLoaderRoute: typeof AppBookingsIdIndexRouteImport
      parentRoute: typeof AppBookingsIdRoute
    }
    '/_app/bookings/$id/assign': {
      id: '/_app/bookings/$id/assign'
      path: '/assign'
      fullPath: '/bookings/$id/assign'
      preLoaderRoute: typeof AppBookingsIdAssignRouteImport
      parentRoute: typeof AppBookingsIdRoute
    }
  }
}

interface AppBookingsIdRouteChildren {
  AppBookingsIdAssignRoute: typeof AppBookingsIdAssignRoute
  AppBookingsIdIndexRoute: typeof AppBookingsIdIndexRoute
}

const AppBookingsIdRouteChildren: AppBookingsIdRouteChildren = {
  AppBookingsIdAssignRoute: AppBookingsIdAssignRoute,
  AppBookingsIdIndexRoute: AppBookingsIdIndexRoute,
}

const AppBookingsIdRouteWithChildren = AppBookingsIdRoute._addFileChildren(
  AppBookingsIdRouteChildren,
)

interface AppRouteChildren {
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppStatesRoute: typeof AppStatesRoute
  AppAssignmentSuccessRoute: typeof AppAssignmentSuccessRoute
  AppBookingsIdRoute: typeof AppBookingsIdRouteWithChildren
  AppDriversIdRoute: typeof AppDriversIdRoute
  AppJobsNewRoute: typeof AppJobsNewRoute
  AppZonesIdRoute: typeof AppZonesIdRoute
  AppBookingsIndexRoute: typeof AppBookingsIndexRoute
  AppDriversIndexRoute: typeof AppDriversIndexRoute
  AppZonesIndexRoute: typeof AppZonesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotificationsRoute: AppNotificationsRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppStatesRoute: AppStatesRoute,
  AppAssignmentSuccessRoute: AppAssignmentSuccessRoute,
  AppBookingsIdRoute: AppBookingsIdRouteWithChildren,
  AppDriversIdRoute: AppDriversIdRoute,
  AppJobsNewRoute: AppJobsNewRoute,
  AppZonesIdRoute: AppZonesIdRoute,
  AppBookingsIndexRoute: AppBookingsIndexRoute,
  AppDriversIndexRoute: AppDriversIndexRoute,
  AppZonesIndexRoute: AppZonesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
